---
- name: Base | Marking Packer build time
  copy:
    content: |
      {{ ansible_date_time.iso8601 }}
    dest: /etc/packer_build_time
    mode: 0644
  become: true

- name: Base | Configuring sshd_config options
  lineinfile:
    line: "{{ item.key }} {{ item.value }}"
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.key }}"
    state: present
  become: true
  loop:
    - key: UseDNS
      value: "no"
    - key: GSSAPIAuthentication
      value: "no"
